luku1 = int(input("Anna ensimmäinen luku: "))
luku2 = int(input("Anna ensimmäinen luku: "))
print("")
if(luku1 > luku2): print("Luku",luku1,"on suurempi.")
if(luku1 < luku2): print("Luku",luku2,"on suurempi.")
if(luku1 == luku2): print("Luvut",luku1,"ja",luku2,"ovat yhtä suuret.")
